// let a = 50;
// var b = 40;

// {
// console.log(b); 
// // console.log(a);
// var b= 90;
// let a = 200;
// function call(){
// //  console.log(b);

// console.log(a);

// let b = 55; 
// var a  = 65;

// console.log(a);

// console.log(b);
// }
// call();

// console.log(a);

// console.log(b);

// }

// console.log(a);

// console.log(b);


// function callMe2(a,b,c){
//     if(a>b){
//         var a=60;
//         let b=50;
//         const c=60;
//          console.log(a,b,c);
//     }
//     console.log(a,b,c);
// }
// callMe2(12,4,5);
// console.log([]==![]);



function callMe2(){
    var a=b=c=60;
console.log(a,b,c);
}
callMe2();

 console.log(a);
 console.log(b);
console.log(c);